events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('index/', views.index),
    path('list/', views.event_list, name='event_list'),
    path('detail/<int:pk>/', views.event_detail, name='event_detail')
]

realworlddjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('events/', include('events.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from utils.models import places_left


class Category(models.Model):
    title = models.CharField(max_length=90,  # максимальная длина поля
                             default='',  # значение по умолчанию для новых объектов
                             verbose_name='Категория'  # название, выводимое на сайте
                             )

    class Meta:
        verbose_name_plural = 'Категории'  # форма единственного числа
        verbose_name = 'Категория'  # форма множественного числа

    def __str__(self):
        return self.title

    def display_event_count(self):
        return self.events.count()


class Feature(models.Model):
    title = models.CharField(max_length=200,  # максимальная длина поля
                             default='',  # значение по умолчанию для новых объектов
                             verbose_name='Свойство события'  # название, выводимое на сайте
                             )

    class Meta:
        verbose_name_plural = 'Свойства события'  # форма единственного числа
        verbose_name = 'Свойство события'  # форма множественного числа

    def __str__(self):
        return self.title


class Event(models.Model):
    title = models.CharField(max_length=200,  # максимальная длина поля
                             default='',  # значение по умолчанию для новых объектов
                             verbose_name='Название'  # название, выводимое на сайте
                             )
    description = models.TextField(default='',  # значение по умолчанию для новых объектов
                                   verbose_name='Описание'  # название, выводимое на сайте
                                   )
    date_start = models.DateTimeField(verbose_name='Дата начала')  # название, выводимое на сайте
    participants_number = models.PositiveSmallIntegerField(
        verbose_name='Количество участников'  # название, выводимое на сайте
    )
    is_private = models.BooleanField(default=False,  # значение по умолчанию для новых объектов
                                     verbose_name='Частное'  # название, выводимое на сайте
                                     )
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, related_name='events',
                                 verbose_name='Категория')
    features = models.ManyToManyField(Feature, related_name='events')
    logo = models.ImageField(upload_to='events/logos/', blank=True, null=True)

    def display_enroll_count(self):
        return self.enrolls.count()

    display_enroll_count.short_description = 'Количество записей'

    def display_places_left(self):
        result = f'{self.participants_number - self.display_enroll_count()} ({places_left(self.display_enroll_count(), self.participants_number)})'
        return result

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[str(self.pk)])

    display_places_left.short_description = 'Осталось мест'

    @property
    def logo_url(self):
        return self.logo.url if self.logo else f'{settings.STATIC_URL}images/svg-icon/event.svg'

    @property
    def rate(self):
        sum_review = 0
        for review in self.reviews.all():
            sum_review += review.rate
        return round(sum_review/self.reviews.count(), 1)

    class Meta:
        ordering = ['date_start', ]
        verbose_name_plural = 'События'  # форма единственного числа
        verbose_name = 'Событие'  # форма множественного числа


class Enroll(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='enrolls')
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE, related_name='enrolls')
    created = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Запись на событие'  # форма единственного числа
        verbose_name = 'Записи на событие'  # форма множественного числа


class Review(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='reviews')
    event = models.ForeignKey(Event, null=True, on_delete=models.CASCADE, related_name='reviews')
    rate = models.PositiveSmallIntegerField(verbose_name='Оценка пользователя')
    text = models.TextField(verbose_name='Текст отзыва')
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Отзыв на событие'  # форма единственного числа
        verbose_name = 'Отзывы на событие'  # форма множественного числа

utils/models.py
MORE50 = '<= 50%'
LESS50 = '> 50%'
SOLD_AUT = 'sold-out'


def places_left(even_seats, participants_number):
    if participants_number != 0:
        if even_seats/participants_number == 1:
            result = SOLD_AUT
        elif even_seats/participants_number <= 0.5:
            result = MORE50
        else:
            result = LESS50
        return result
    return f'{participants_number} = 0'

events/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from events.models import Event, Feature, Category


# Create your views here.

def index(request):
    return HttpResponse('Hello, World')


def event_list(request):
    template_name = 'events/event_list.html'
    event_objects = Event.objects.all()
    category_objects = Category.objects.all()
    feature_objects = Feature.objects.all()

    context = {
        'event_objects': event_objects,
        'category_objects': category_objects,
        'feature_objects': feature_objects,
        'user': request.user,

    }
    return render(request, template_name, context)


def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    context = {
        'event': event,
    }
    return render(request, 'events/event_detail.html', context)

events/templates/events/event_list.html
<!DOCTYPE html>
{% load static %}
{% load eventstags %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Real World Django - События</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- Project style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>

<div class="vertical-layout">

    <!-- Start LEFT_MENU -->
    <div class="leftbar">
        <div class="logobar">
            <a href="index.html" class="logo logo-large">
                <img src="{% static 'images/svg-icon/logo.svg' %}" alt="logo" style="height: 40px">
            </a>
        </div>
        <ul class="vertical-menu" id="vertical-menu">
            <li class="vertical-menu-item">
                <span>Главное</span>
                <ul class="vertical-submenu">
                    <li><a href="{% url 'events:event_list' %}">События</a></li>
                    <li><a href="mail.html">Подписчики</a></li>
                </ul>
            </li>
            <li class="vertical-menu-item">
                <span>Аккаунт</span>
                <ul class="vertical-submenu">
                    <li><a href="profile.html">Мой аккаунт</a></li>
                    <li><a href="#">Изменить пароль</a></li>
                    <li><a href="#">Сбросить пароль</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- menu for mobile -->
    <div class="topbar-mobile">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="mobile-logobar" style="max-width: 40px">
                    <a href="#" class="mobile-logo">
                        <img src="{% static 'images/svg-icon/logo.svg' %}" class="img-fluid" alt="logo">
                    </a>
                </div>
                <div class="mobile-togglebar">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <div class="menubar">
                                <a class="menu-hamburger" href="#" id="menu-hamburger">
                                    <img src="{% static 'images/svg-icon/collapse.svg' %}"
                                         class="img-fluid menu-hamburger-collapse"
                                         alt="collapse">
                                    <img src="{% static 'images/svg-icon/close.svg' %}"
                                         class="img-fluid menu-hamburger-close"
                                         alt="close">
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="d-md-none" style="height: 90px"></div>
    <!-- End LEFT_MENU -->

    <!-- Start MAIN_CONTAINER -->
    <div class="rightbar">

        <!-- Start TOP_BAR -->
        <div class="container-fluid bg-white py-3">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto text-center ms-4">
                    <h4>События</h4>
                </div>
                <div class="col-auto text-center me-4">
                    {% if user.is_authenticated %}
                    <a href="#" class="btn btn-outline-primary">+ Добавить событие</a>
                    {% else %}
                    <a href="#" class="btn btn-outline-primary">Войти</a>
                    <a href="#" class="btn btn-primary">Регистрация</a>
                    {% endif %}

                </div>
            </div>
        </div>
        <!-- End TOP_BAR -->

        <!-- Start CONTAINER_BAR -->
        <div class="container-fluid mt-3">
            <div class="row mb-4">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-body">
                            <form>
                                <div class="row row-cols-lg-auto g-3 align-items-start">
                                    <div class="col-12">
                                        <label for="category" class="form-label">Категория:</label>
                                        <select class="form-select" id="category">
                                            <option selected="">....................</option>
                                            {% for item in category_objects %}
                                            <option value="{{ item.id }}">{{ item.title }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <label for="features" class="form-label">Свойства:</label>
                                        <select class="form-select" multiple="" id="features">
                                            {% for item in feature_objects %}
                                            <option value="{{ item.id }}">{{ item.title }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-12 d-md-flex">
                                        <div class="mx-1">
                                            <label for="id_date_start" class="form-label">Дата начала</label>
                                            <input type="date" class="form-control" id="id_date_start">
                                        </div>
                                        <div class="mx-1">
                                            <label for="id_date_end" class="form-label">Дата окончания</label>
                                            <input type="date" class="form-control" id="id_date_end">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-12 d-md-flex">
                                        <div class="form-check me-3">
                                            <input class="form-check-input" type="checkbox" value="" id="is_private">
                                            <label class="form-check-label" for="is_private">
                                                Private
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="is_available">
                                            <label class="form-check-label" for="is_available">
                                                Есть места
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-3">
                                        <button type="submit" class="btn btn-primary">Фильтровать</button>
                                        <a href="/events/list/" class="btn btn-outline-danger">Сбросить</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#" data-test="p_start">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_previous">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_1">1</a></li>
                <li class="page-item active"><a class="page-link" href="#" data-test="p_2">2</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_3">3</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_next">Next</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_end">&raquo;</a></li>
            </ul>
            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4">
            {% for event in event_objects %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">{{ event.title }}</h5>
                            {% if event.is_private %}
                            <span data-test="is_private" class="badge bg-dark">Private</span>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <h3>{{ event.display_enroll_count }} из {{ event.participants_number }}</h3>
                            <p>участников</p>
                            <ul class="py-2">
                                {% for feature in event.features.all %}
                                <li>{{ feature.title }}</li>
                                {% endfor %}
                            </ul>
                            <p>
                                дата: <strong data-test="date_start">{{ event.date_start|eventsdate }}</strong>
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="{{ event.get_absolute_url }}" class="btn btn-success">Смотреть</a>
                            <a href="event_update.html" class="btn btn-outline-primary" title="Изменить">
                                <i class="bi bi-pencil-square"></i>Изменить
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        <!-- End CONTAINER_BAR -->

        <!-- Start FOOTER -->
        <div style="height: 70px"></div>
        <div class="footerbar">
            <footer class="footer">
                <p class="mb-0">© Pumpskill. Real World Django</p>
            </footer>
        </div>
        <!-- End FOOTER -->

    </div>
    <!-- End MAIN_CONTAINER -->

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>